tests: utils: Improve assert_equal_help output
Earlier, assert_equal_help showed the actual output and expected result
next to each other:

ASSERT: line (128): expected:<31> but was:<32>

Now it prints in new lines. New format is:

ASSERT: line (128): Use this year
Expected Result: 31
-> Actual Result: 32

Also the color of Expected result is set to blue and Actual Result to
Red

Closes: #554

Signed-off-by: RaviRahar <ravirahar33@gmail.com>